// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh_m8J2wiC2OcNXBILiqgRqp_kXR91Bh8',
    appId: '1:426822788845:web:95334a06474a727eb64ee4',
    messagingSenderId: '426822788845',
    projectId: 'trainingcourse-98b15',
    authDomain: 'trainingcourse-98b15.firebaseapp.com',
    storageBucket: 'trainingcourse-98b15.appspot.com',
    measurementId: 'G-T4D1NMNDBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2FLpIhPqpg9Z6oSqaTTqvtrR1vj3H2kg',
    appId: '1:426822788845:android:b4dde009e1824d19b64ee4',
    messagingSenderId: '426822788845',
    projectId: 'trainingcourse-98b15',
    storageBucket: 'trainingcourse-98b15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX-9aGrB4WXuFSsQZxrMrSwIOVx7RigLo',
    appId: '1:426822788845:ios:2832b0ddd0b0bb54b64ee4',
    messagingSenderId: '426822788845',
    projectId: 'trainingcourse-98b15',
    storageBucket: 'trainingcourse-98b15.appspot.com',
    iosBundleId: 'com.example.sectionProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX-9aGrB4WXuFSsQZxrMrSwIOVx7RigLo',
    appId: '1:426822788845:ios:2832b0ddd0b0bb54b64ee4',
    messagingSenderId: '426822788845',
    projectId: 'trainingcourse-98b15',
    storageBucket: 'trainingcourse-98b15.appspot.com',
    iosBundleId: 'com.example.sectionProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh_m8J2wiC2OcNXBILiqgRqp_kXR91Bh8',
    appId: '1:426822788845:web:0a8d24946bd96346b64ee4',
    messagingSenderId: '426822788845',
    projectId: 'trainingcourse-98b15',
    authDomain: 'trainingcourse-98b15.firebaseapp.com',
    storageBucket: 'trainingcourse-98b15.appspot.com',
    measurementId: 'G-22E26CNMGJ',
  );
}
